/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 57544baa7b0b1b586dffcb9783b6f767)
interface __BaseEnv_CloudflareBindings {
	BACKUP_BUCKET: R2Bucket;
	ARTIFACTS: Artifacts;
	AI: Ai;
	ASSETS: Fetcher;
	BACKUP_BUCKET_NAME: string;
	WATCH_NAMESPACE: string;
	WATCH_REPO: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DEPLOY_ACCOUNT_ID: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").CiSandbox>;
	HEALER: DurableObjectNamespace<import("./src/index").Healer>;
	REGISTRY: DurableObjectNamespace<import("./src/index").RunRegistry>;
	CI_WORKFLOW: Workflow<Parameters<import("./src/index").CI['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CiSandbox" | "Healer" | "RunRegistry";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKUP_BUCKET_NAME" | "WATCH_NAMESPACE" | "WATCH_REPO" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_DEPLOY_ACCOUNT_ID">> {}
}
